#
language: java
dist: trusty
jdk: oraclejdk8
branches:
  only:
    - develop
install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
script:
  - mvn -P${TRAVIS_BRANCH} clean install
# FIXME include deploy when ready
