import java.util.zip.ZipFile

println("When run in the directory containing the Sling Launchpad / Starter\n" +
        "it generates a file sling-dependencies.xml containing information from the\n" +
        "META-INF/maven file contained in all jars below the directory sling/ .\n" +
        "(Composum bundles are excluded.)")

File topfile = new File("sling").canonicalFile

def pom = new FileWriter("sling-depsfromjars.xml")
pom.append("""
    <!-- Generated by ExtractStarterDependenciesroovy. -->
""")


List<String> entries = new ArrayList<String>();

topfile.traverse(nameFilter: ~/.*\.jar/) { File it ->
    def jar = new ZipFile(it)
    String pomentry = ""
    jar.entries().find { it.name.endsWith("/pom.properties") && it.name.contains("META-INF/maven") }.each {
        Properties props = new Properties()
        props.load(jar.getInputStream(it))
        def version = props.getProperty("version")
        def group = props.getProperty("groupId")
        def artifact = props.getProperty("artifactId")
        pomentry = pomentry + """
        <dependency>
            <groupId>$group</groupId>
            <artifactId>$artifact</artifactId>
            <version>$version</version>
            <scope>provided</scope>
        </dependency>
"""
    }
    // println(pomentry)
    if (!"".equals(pomentry) && !pomentry.contains("com.composum") && !entries.contains(pomentry)) {
        entries.add(pomentry)
    }
    pomentry = ""
    jar.close()
}

Collections.sort(entries)
for (item in entries) {
    pom.append(item)
}
pom.close()

println("Wrote sling-dependencies.xml")
